增加+1功能；增加显示群名片功能；增加角色台词撤回功能
Arkfans/Arktalk pull request #1
Opened 2022-12-09 14:47 UTC by 1MLightyears

旁白居中 和 从素材库新增头像时自动填角色名 下次pr写

2022-12-09 16:40 UTC, meeboo3 requested changes
如果可以，快捷@请支持移动端

2022-12-09 16:46 UTC, meeboo3 commented on src/render/arknights/Render.vue
> +                            <!-- TODO 应当把column-count+gap的这个写法应用到所有有并列的el-button的容器上-->
样式修改后，似乎两个button并不能并排？

2022-12-09 17:07 UTC, meeboo3 commented
1、使用+1时，需要手动切换角色，是否可以选择多个角色进行复读，减少操作量
2、关于撤回，建议抽象为“模板消息”
3、群名片的显示，会加入v0.0.5的渲染设置作为可选功能

2022-12-09 17:10 UTC, meeboo3 commented on src/render/arknights/Render.vue
> +        // FIXME:(20221209) 没看懂文档里怎么调el-select的focus 这里先hack了= =
[模板引用](https://cn.vuejs.org/guide/essentials/template-refs.html) 参考此文档

2022-12-10 11:39 UTC, 1MLightyears commented on src/render/arknights/Render.vue
> +                            <!-- TODO 应当把column-count+gap的这个写法应用到所有有并列的el-button的容器上-->
我换别的平台看一下；这个在我的Firefox 103.0.2 (64 位)上是正常的

2022-12-10 12:07 UTC, 1MLightyears commented
> 1、使用+1时，需要手动切换角色，是否可以选择多个角色进行复读，减少操作量 2、关于撤回，建议抽象为“模板消息” 3、群名片的显示，会加入v0.0.5的渲染设置作为可选功能

1. 关于多个角色复读：可以但我感觉不是特别好，因为首先需要先实现角色的el-scrollbar的多选功能；其次就是由于发言只能单个角色进行，多选角色时的发言如何处理，这点有可能造成歧义；
 我觉得可以这样实现：首先允许角色多选，然后发言时对每个选中的角色，按选中顺序，都发送一遍textarea内的内容。实现上就是遍历currChar（其实应该叫selectedChar了）然后挨个push到chats里
2. 关于模板消息：模板消息有一个问题就是需要有一个格式字符串解析器，因为类似于“撤回”“拍一拍”之类的功能会需要用到角色名，需要动态修改内容；这个具体怎么实现，以及入口放在哪里（我觉得放在齿轮旁边搞一个和角色相同的el-scrollbar是个不错的选择）

2022-12-10 14:28 UTC, meeboo3 commented
> 1. 关于多个角色复读：可以但我感觉不是特别好，因为首先需要先实现角色的el-scrollbar的多选功能；其次就是由于发言只能单个角色进行，多选角色时的发言如何处理，这点有可能造成歧义；
>    我觉得可以这样实现：首先允许角色多选，然后发言时对每个选中的角色，按选中顺序，都发送一遍textarea内的内容。实现上就是遍历currChar（其实应该叫selectedChar了）然后挨个push到chats里
> 2. 关于模板消息：模板消息有一个问题就是需要有一个格式字符串解析器，因为类似于“撤回”“拍一拍”之类的功能会需要用到角色名，需要动态修改内容；这个具体怎么实现，以及入口放在哪里（我觉得放在齿轮旁边搞一个和角色相同的el-scrollbar是个不错的选择）

1. 角色多选发言确实是个糟糕的注意，但我想说的其实是单独针对复读做一个多选el-dialogue，关于输入，我建议在编辑对话中新增一个“复读”button，这样所有的消息类型都能很方便地复读
2. 关于模板消息，动态内容建议是 `{char}撤回了一条{str:消息}`，格式为 `{type:default?}`，并在插入时提供input/select；入口参考[增加拓展框](https://github.com/Arkfans/Arktalk/commit/2a76513810efb756d542a95b261026238bff2d89)，齿轮旁并不建议，消息的输入都集中在operateBar上半部分，没有特殊含义放在下半部分会很怪
另：模板消息的预期发送流程 `模板消息 > 选择模板 > 输入动态内容 > 发送`

2022-12-10 14:58 UTC, 1MLightyears commented
> 入口参考[增加拓展框](https://github.com/Arkfans/Arktalk/commit/2a76513810efb756d542a95b261026238bff2d89)

拓展框的效果我大概想象出来了...吧我等你dev合进main里之后再同步过来再修改吧，我这边功能都做好了，改入口的时候DOM调下位置应该就可以了
关于复读，如果要像你说的那样做的话，我是否要去掉“+1”？
关于模板消息，现在的实现其实是照着Python的`eval()`的模型写的...我其实没太理解“在插入时提供input/select”是什么意思...

2022-12-10 15:41 UTC, meeboo3 commented
>关于复读，如果要像你说的那样做的话，我是否要去掉“+1”？ 关于模板消息，现在的实现其实是照着Python的`eval()`的模型写的...我其实没太理解“在插入时提供input/select”是什么意思...

1. 不用，但编辑消息中的复读还是有必要添加，因为目前的+1方式并不支持移动端（溢出屏幕）
2. 搓了一个demo，实际使用时需要id作为标识，因此格式改为 `{type:id:default?}`

![%C}L9N9ZT8CJ 2$0UUT052M](https://user-images.githubusercontent.com/118372959/206862589-30ccba80-e7d0-4c28-bb84-b9309210ad41.png)

3. 记得处理DataControl.save，这有关自动保存（如果看不懂，合并时我会操作，这方面以后会增加文档）

2022-12-10 15:46 UTC, 1MLightyears commented
你是想动态生成模板内容而不是给出几个固定的模板内容...但这要求用户会写模板呀
模板字符串编辑方面应该有更好的方案，我之后会搓一个demo出来 来看一下
（没有什么移动端开发经验真是抱歉啊:cry:）

2022-12-16 03:20 UTC, closed without merging